[WIP]タスク削除機能実装
mofmof/training-miura pull request #16
Opened 2022-09-01 02:19 UTC by shinji128

2022-09-01 07:44 UTC, shwld reviewed
レビューりました

2022-09-01 07:44 UTC, shwld commented on app/graphql/mutations/delete_task.rb
> +      Task.find(id).delete
`delete` を使っている理由はありますか?

`destroy` のほうが一般的で、 `delete` を使うシーンは割と理由とセットじゃないといけない気がしますね。

あとエラー処理をしたいです。

`destroy` の結果を確認するのか、 `destroy!` にしてrescueで拾うのか。
後者のほうが手軽だし、まずは後者からはじめてみても良いかもと思いました。

エラーが起きても気づけないのは回避したい。

2022-09-01 07:44 UTC, shwld commented on app/javascript/components/TopPage.tsx
> +    setInterval(() => {
もしこのように flashMsgのありなしで処理をするかどうか分岐したい場合、Reactでは `useEffect` を使います。

```ts
useEffect(() => {
  setInterval(() => {
    setMessage(flashMsg.msg);
  }, 2000);
}, [flashMsg])
```

みたいにすると想定通りになると思います。

更に言うと、この実装多分stateは必要なくて

flashMsgがあったら直接画面に描画するで良いと思います。
その上で、メッセージ表示を消したい場合は、routerの方でstateを消す遷移を起こすのが良いかと

2022-09-01 07:44 UTC, shwld requested changes
👁️

2022-09-01 07:46 UTC, shwld commented on app/javascript/components/TopPage.tsx
> +    setInterval(() => {
あ、でもこれはsetTimeoutで表示を遅らせたいという意図もあるか。。。
それは多分cssのアニメーションで対応するのがよりベターかもですね。そこまではしなくてもいいですが

2022-09-01 07:48 UTC, shwld commented on app/javascript/components/TopPage.tsx
> +    setInterval(() => {
もし2秒遅らせるのを実装したい場合は、 上のuseEffectのパターンで良さそうです

2022-09-01 07:54 UTC, shinji128 commented on app/javascript/components/TopPage.tsx
> +    setInterval(() => {
2秒後にメッセージが削除されるように実装しました。
リロードしてもメッセージが表示され続けてたので邪魔かなと思いまして。
実装はuseEffectも試してみたのですが、無限レンダーが発生して断念しました。。。

2022-09-01 07:58 UTC, shinji128 commented on app/graphql/mutations/delete_task.rb
> +      Task.find(id).delete
```delete```の理由特にありません。
確かに今までも```delete```使ったことなかったです。
```destroy!```で修正します！

2022-09-02 01:05 UTC, shwld commented on app/javascript/components/TopPage.tsx
> +    setInterval(() => {
あー、そうか2秒後に消したいのか！
読み違えてました

2022-09-02 01:08 UTC, shwld commented on app/javascript/components/TopPage.tsx
> +    setInterval(() => {
@shinji128 

```
useEffect(() => {
  if (!flashMsg) return // メッセージが空なら何もしない
  setMessage(flashMsg);
  setInterval(() => {
    setMessage('');
  }, 2000);
}, [flashMsg, setMessage])
```

こんなんどうでしょう?

2022-09-02 01:10 UTC, shwld commented on app/javascript/components/TopPage.tsx
> +    setInterval(() => {
```ts
useEffect(() => {
  if (!flashMsg) return // メッセージが空なら何もしない
  setInterval(() => {
    router.replace('/', {})
  }, 2000);
}, [flashMsg])
```

みたいなのもいける?

2022-09-02 01:38 UTC, shinji128 commented on app/javascript/components/TopPage.tsx
> +    setInterval(() => {
[7ef7475](https://github.com/mofmof/training-miura/pull/16/commits/7ef74758e0725fb34f0281ef2d07fea365a84343)
ありがとうございます！
実装できました！
```router.replace('/', {})```は```navigate("/", {});```
に書き換えてます。

2022-09-02 06:39 UTC, shinji128 commented on app/graphql/mutations/delete_task.rb
> +      Task.find(id).delete
@shwld 
タスク削除時の例外処理で詰まっています。
・やりたいこと
例外発生時に"タスクを削除できませんでした"と表示させたい
・できていないこと
例外が発生したことをフロントでキャッチできていない
```typescript
const [deleteTask, { data, loading, error }] = useDeleteTaskMutation({
    refetchQueries: ["tasks"],
  });
deleteTask()
console.log(error)
```
で表示できそうな気がしているのですが、errorの中身がundefindでした。
他には公式参考にapollo-serverを使ってみたのですが、よくわからなかったです。。。
公式；https://www.apollographql.com/docs/apollo-server/data/errors/

2022-09-05 07:11 UTC, shinji128 commented on app/javascript/components/TopPage.tsx
> +    setInterval(() => {
[3ade6dd](https://github.com/mofmof/training-miura/pull/16/commits/3ade6dd9103b79fa3dea7444b3b04ba92fcdd568)
タイマーがリセットされていなかったので、
useRefで値を監視し、タイマーをリセットするように修正しました。
また、フラッシュメッセージをコンポーネント化しました。

2022-09-07 00:17 UTC, shwld requested changes
ちょっと見直してほしいところが

2022-09-07 00:17 UTC, shwld commented on app/javascript/components/FlashMessage.tsx
> +    const interval = setInterval(() => {
これ最初からsetIntervalだったので引っ張られてしまいましたが、setTimeoutでいいですね...

2022-09-07 00:17 UTC, shwld commented on app/javascript/components/FlashMessage.tsx
> +  const flashMsg = useRef(locationState?.msg);
useRefないと動かない?
修正前の状態ではなかったので、不要そうに見えましたが、必要な理由が気になる

2022-09-07 00:17 UTC, shwld commented on app/graphql/mutations/delete_task.rb
> +      Task.find(id).destroy!
👍

2022-09-07 00:17 UTC, shwld commented on app/javascript/components/TaskDelete.tsx
> +    deleteSuccessRedirect();
`deleteTask` 自体は非同期じゃないでしょうか?(awaitが必要?)
また、エラーかどうかに関わらずここ通るような気がしますがどうですか?

2022-09-07 04:31 UTC, shinji128 commented on app/javascript/components/TaskDelete.tsx
> +    deleteSuccessRedirect();
[5f6fba5](https://github.com/mofmof/training-miura/pull/16/commits/5f6fba59302b23a271a214967df496cba449b097)
ご指摘の通りエラーの有無に関わらず```deleteSuccessRedirect```が実行されていました。
mutationのオプションを調べてローカルで動き確認したところ、
```onError```エラー発生時のみ実行
```onCompleted```処理成功時のみ実行
という結果だったので、オプションで条件分岐させると正常に動作しました。
参考：https://qiita.com/setsumaru1992/items/3d77ba5ed883ca89b348

2022-09-07 04:34 UTC, shinji128 commented on app/javascript/components/FlashMessage.tsx
> +  const flashMsg = useRef(locationState?.msg);
[6fc8485](https://github.com/mofmof/training-miura/pull/16/commits/6fc8485d3d05c8856218f72a6fa1e2cd2083a43a)
TaskDeleteコンポーネントを修正したところ、useRef使用せずとも実装できました。
また、setTimeoutに変更しました。

2022-09-07 04:35 UTC, shinji128 commented on app/javascript/components/FlashMessage.tsx
> +    const interval = setInterval(() => {
ありがとうございます。
setTimeoutに修正しました。

2022-09-08 01:44 UTC, merged