[WIP]ログイン機能実装
mofmof/training-miura pull request #18
Opened 2022-09-09 02:18 UTC by shinji128

2022-09-16 00:28 UTC, shwld requested changes

2022-09-16 00:28 UTC, shwld commented on app/javascript/components/Logout.tsx
> +  axios.delete("/logout", { withCredentials: true }).then(() => {
ここはuseEffectを使うべきだとおもいました。いやなんかそうとも言い切れない気もする。後で話したいです

2022-09-16 00:28 UTC, shwld commented on app/controllers/application_controller.rb
> +      domain: 'localhost',
localhost固定?

2022-09-16 00:28 UTC, shwld commented on app/graphql/mutations/sign_up.rb
> +      user = User.create(params.to_h)
ここだけ修正お願いしたいです。
エラーの場合の処理

2022-09-16 00:28 UTC, shwld commented on app/javascript/application.tsx
> +axios.get("/login");
これ何の処理か後で聴きたい

2022-09-16 05:19 UTC, shinji128 commented on app/controllers/application_controller.rb
> +      domain: 'localhost',
[Cookeisのドメインを開発・本番環境で切り替わるように修正](https://github.com/mofmof/training-miura/pull/18/commits/c53493f3f9124b04550ee3355edd3c8c437f87e8)
変更し忘れていたので修正しました。

2022-09-16 06:15 UTC, shinji128 commented on app/graphql/mutations/sign_up.rb
> +      user = User.create(params.to_h)
現状だとバリデーションエラーの内容が出ていない。
出ているエラー不適切

2022-09-20 00:41 UTC, shinji128 commented on app/javascript/components/Logout.tsx
> +  axios.delete("/logout", { withCredentials: true }).then(() => {
[useEffect内でログアウトするよう修正](https://github.com/mofmof/training-miura/pull/18/commits/4f5cce867d357432f8a8bda6a832f35d91fdc7a7)

2022-09-20 03:00 UTC, shinji128 commented on app/graphql/mutations/sign_up.rb
> +      user = User.create(params.to_h)
[バリデーションメッセージが表示されるように修正](https://github.com/mofmof/training-miura/pull/18/commits/78583a57561f300c8521e4cbe8fddb7ba08cc466)

use作成ができなかった場合に、例外を発生させバリデーションメッセージを返すように修正

![バリデーション](https://user-images.githubusercontent.com/81057658/191157235-e8293bb4-8530-4b2f-a313-b4cfb224c8c9.png)

2022-09-20 03:04 UTC, shinji128 commented on app/javascript/application.tsx
> +axios.get("/login");
[コメント追加、CSRFトークンセット用リクエストをRootに変更](https://github.com/mofmof/training-miura/pull/18/commits/860db06c6b1e4dba82edde680f0bffd674b3dca6)
- 処理内容をコメント追記
- CSRFトークン用リクエストなので、URLをRootに変更

2022-09-20 03:07 UTC, merged

2022-09-20 05:00 UTC, shinji128 commented on app/controllers/application_controller.rb
> +      domain: 'localhost',
https://github.com/mofmof/training-miura/pull/27