userとtaskの関連付け設定
mofmof/training-miura pull request #21
Opened 2022-09-12 04:51 UTC by shinji128

2022-09-16 00:29 UTC, shwld commented
> マージされていないプルリクの差分を引き継いで今回のプルリクを作成したが、このやり方で特に問題ないのか確認して欲しいです。

はい、プルリクにその旨記載あるので、問題ないです！ 👍

2022-09-16 00:33 UTC, shwld requested changes

2022-09-16 00:33 UTC, shwld commented on app/graphql/mutations/create_task.rb
> +      task = context[:current_user].tasks.create(params.to_h)
current_userがない場合どうなる?
taskのcreateが失敗した場合どうなる?

2022-09-16 00:33 UTC, shwld commented on app/graphql/mutations/delete_task.rb
> +      context[:current_user].tasks.find(id).destroy!
current_userがない場合どうなる?

2022-09-16 00:33 UTC, shwld commented on app/graphql/mutations/create_task.rb
> +      task = context[:current_user].tasks.create(params.to_h)
authorize?メソッドを使うと良いかもしれません

2022-09-20 07:07 UTC, shinji128 commented on app/graphql/mutations/create_task.rb
> +      task = context[:current_user].tasks.create(params.to_h)
[authorizedメソッドで認可機能実装](https://github.com/mofmof/training-miura/pull/21/commits/2de0b78ee5b3a90ca0c8937866a80cc23cc96404)
[タスクmutationの継承元修正、作成・編集失敗時の処理修正](https://github.com/mofmof/training-miura/pull/21/commits/fdf640003c9feb8a11e7f37066edbd4f5cb14714)
authorized?メソッドで未ログインの場合にmutationを実行できないように修正

2022-09-20 07:07 UTC, merged