終了間近のタスクをメール通知で知らせる機能実装
mofmof/training-miura pull request #28
Opened 2022-09-22 08:25 UTC by shinji128

## 実装内容
期限が前日および当日かつ未完了のタスクを毎日AM10:00に通知する。

## 追加gem
- whenever （定期実行用）
- letter_opener_web　（開発環境でのメール確認用）

## 備考
メールはActionMailerで実装

## 画像
![html](https://user-images.githubusercontent.com/81057658/191696706-508d4017-de30-42b2-93bd-1f77c665dd0b.png)
![plain text](https://user-images.githubusercontent.com/81057658/191696719-9f33074e-52e8-4d69-816c-aa7086961bf1.png)

2022-09-27 02:29 UTC, shwld requested changes
find_eachは要修正。他は確認したいです

2022-09-27 02:29 UTC, shwld commented on app/mailers/user_mailer.rb
> +    @tasks = @user.tasks.limit_within_one_day
👍

2022-09-27 02:29 UTC, shwld commented on config/schedule.rb
> +ENV.each { |k, v| env(k, v) }
whenever使ったこと無いんですが、これはどういう処理ですか?

2022-09-27 02:29 UTC, shwld commented on config/schedule.rb
> +ENV.each { |k, v| env(k, v) }
job_typeっていうのは指定いらない?

2022-09-27 02:29 UTC, shwld commented on lib/tasks/task_limit_approach.rake
> +    users = User.all
こういう処理をする際にはメモリ的に `User.find_each` がおすすめです。

2022-09-27 02:29 UTC, shwld commented on lib/tasks/task_limit_approach.rake
> +      UserMailer.with(to: user.email).task_limit_approach.deliver_now
エラーになった場合どうなるかシミュレーションしておきたい

2022-09-27 03:47 UTC, shinji128 commented on config/schedule.rb
> +ENV.each { |k, v| env(k, v) }
>whenever使ったこと無いんですが、これはどういう処理ですか?

```ruby
set :environment, rails_env
```
環境を指定しています。```rails_env = ENV['RAILS_ENV'] || :development```でrails_envを定義していますが、
```set :environment, ENV['RAILS_ENV']```で良い気がしました。

```ruby
set :output, 'log/cron.log'
```
ログを吐き出す場所を指定しています。
```ruby
ENV.each { |k, v| env(k, v) }
```
docker内の環境変数をcronに渡しているという解釈です。
あまり深く理解できてないです。
https://qiita.com/rerofumi/items/fc0126c4e985b78f769b

> job_typeっていうのは指定いらない?
```ruby
job_type :command, ":task :output"
job_type :rake,    "cd :path && :environment_variable=:environment :bundle_command rake :task --silent :output"
job_type :script,  "cd :path && :environment_variable=:environment :bundle_command script/:task :output"
job_type :runner,  "cd :path && :bundle_command :runner_command -e :environment ':task' :output"
```
job_typeについて知らなかったので調べました。
wheneverにデフォルトで4つのjob_typeが定義されていて、下記のように実行するタスクの頭にjob_typeを指定します。今回はrakeを指定していますが、新たなjob_typeの追加、--silentのようなオプション変更、pathが通っていない時に再定義するようでした。
```ruby
rake 'task_limit:task_limit_approach'
```

2022-09-29 00:23 UTC, shwld commented on config/schedule.rb
> +ENV.each { |k, v| env(k, v) }
ありがとうございます！勉強になりました

2022-09-29 06:10 UTC, shwld approved these changes

2022-09-29 07:27 UTC, merged