利用者はタスクの一覧が長くなっても見やすいようにしたい
mofmof/training-miura pull request #36
Opened 2022-10-06 02:21 UTC by shinji128

2022-10-06 02:57 UTC, shwld requested changes
レビューしました!

2022-10-06 02:57 UTC, shwld commented on db/fixtures/development/01_user.rb
> +  User.create!(name: "ユーザー#{i}", email: "user#{i}@example.com", password: "user#{i}", password_confirmation: "user#{i}")
seed_fu使ってないように見えますが、問題ない?
使わないならgem削除しても良い気がしました

2022-10-06 02:57 UTC, shwld commented on app/javascript/components/Tasks.tsx
> +    setFirst((first) => first + 20);
これChromeのネットワークタブでGraphQLのレスポンスを確認してみて欲しいです。
ページネーションの目的である、サーバー負荷軽減の問題が解決してないと思いました。

2022-10-06 02:57 UTC, shwld commented on app/graphql/queries/tasks_type.rb
> +    type ObjectTypes::Task.connection_type, null: false
👍

2022-10-06 07:10 UTC, shinji128 commented on db/fixtures/development/01_user.rb
> +  User.create!(name: "ユーザー#{i}", email: "user#{i}@example.com", password: "user#{i}", password_confirmation: "user#{i}")
本番・開発環境でテストデータを分ける可能性もあったのでファイルを分けて記述しました。
ファイルを分けるとseed_fuでしかテストデータが生成されないという認識です。
確認のためDBリセットしてrails db:seedで実行するとテスト生成されませんでした。
使い方勘違いしてたらすいません。。。

2022-10-06 07:27 UTC, shwld commented on app/javascript/components/Tasks.tsx
> +        {tasks?.pageInfo.hasNextPage && "もっとみる"}
hasNextPageじゃない時空なのちょっと気になります

2022-10-06 08:54 UTC, shwld commented on db/fixtures/development/01_user.rb
> +  User.create!(name: "ユーザー#{i}", email: "user#{i}@example.com", password: "user#{i}", password_confirmation: "user#{i}")
seed_fu使うときって User.seedみたいに使う気がしましたが、これでもいいんでしたけ

2022-10-06 09:05 UTC, shinji128 commented on db/fixtures/development/01_user.rb
> +  User.create!(name: "ユーザー#{i}", email: "user#{i}@example.com", password: "user#{i}", password_confirmation: "user#{i}")
ファイル分けると```rails db:seed_fu```コマンドでしかデータ作成されないみたいですね
seeds.rbファイルに記述した場合のみ```rails db:seed```コマンドで作成できるみたいです？

2022-10-07 00:35 UTC, shwld commented on db/fixtures/development/01_user.rb
> +  User.seed(name: "ユーザー#{i}", email: "user#{i}@example.com", password: "user#{i}", password_confirmation: "user#{i}")
seed_fuのメリットは `db:seed_fu` タスクを複数回実行することができる点にあります。
User.seedメソッドは、再実行したときにデフォルトでは同じ `id` を探してあれば、更新という挙動になります。
なので、idも指定しておかないとあまり旨味がなさそう

2022-10-07 02:03 UTC, shwld commented on db/seeds.rb
> +  User.seed(name: "ユーザー#{i}", email: "user#{i}@example.com", password: "user#{i}", password_confirmation: "user#{i}")
あれ、seed_fuけしてもseedメソッドってある?

2022-10-07 02:14 UTC, shinji128 commented on db/seeds.rb
> +  User.seed(name: "ユーザー#{i}", email: "user#{i}@example.com", password: "user#{i}", password_confirmation: "user#{i}")
ありました！
違いについては生成したデータを返すかどうかみたいでした。
createとseed両方で試したのですが、seedだとターミナルに作成したデータが全て返されました。
そのほかの違いは見られなかったです。
https://docs.ruby-lang.org/ja/latest/method/Random/i/seed.html

2022-10-07 02:27 UTC, shwld commented on db/seeds.rb
> +  User.seed(name: "ユーザー#{i}", email: "user#{i}@example.com", password: "user#{i}", password_confirmation: "user#{i}")
このドキュメントは別のseedですね
bundle installし直したら消えるきがする

2022-10-07 04:17 UTC, shwld approved these changes

2022-10-07 05:07 UTC, merged