[WIP]Labelテーブル追加
mofmof/training-miura pull request #40
Opened 2022-10-17 02:50 UTC by shinji128

2022-10-19 03:16 UTC, shwld requested changes
全体的に良い感じだと思いました！

追加時のエラーメッセージのとこがRequest changesです
他のコメントについてはおまかせします！
やるとしても別ストーリーとかでいいかも...?

2022-10-19 03:16 UTC, shwld commented on app/javascript/components/TaskLabels.tsx
> +      navigate("/labels", { state: { msg: "削除失敗" } });
メッセージ内容ミスってますね

2022-10-19 03:16 UTC, shwld commented on app/javascript/components/LabelDelete.tsx
> +    refetchQueries: ["labels"],
ホントはタスク側もリフェッチ必要な案件かも...
でもこれは悩ましい問題なのでこれでいいと思います！

2022-10-19 03:36 UTC, shinji128 commented on app/graphql/mutations/remove_label_to_task.rb
> +  class RemoveLabelToTask < LoginRequiredMutation
[名称変更 removeLabelTotask → removeLabelFromTask](https://github.com/mofmof/training-miura/pull/40/commits/168d1ba00305619b0eca7a01c9b398465ee4f3aa)
変更しました！
deepLで確認しましたがto,from両方意味同じでしたが、確かにfromの方がわかりやすい気がしました

2022-10-19 03:39 UTC, shinji128 commented on app/graphql/queries/task_labels_type.rb
> +  class TaskLabelsType < Queries::LoginRequiredQuery
もう少し詳しく聞きたいので定例のタイミングで改めて教えてください。。。

2022-10-19 03:53 UTC, shinji128 commented on app/javascript/components/CreateLabelForm.tsx
> +    setName("");
[ラベル作成入力フォームを空にするタイミングをonCompletedのみに変更](https://github.com/mofmof/training-miura/pull/40/commits/7118c840201b1008c59d70e3993a7b34d02103ca)
確かにでした。

2022-10-19 03:54 UTC, shinji128 commented on app/javascript/components/TaskLabels.tsx
> +      navigate("/labels", { state: { msg: "削除失敗" } });
[文言修正](https://github.com/mofmof/training-miura/pull/40/commits/355bdebc13535b3b02e5906c92b0f506d1e4a0c3)
追加失敗に修正しました。

2022-10-19 03:55 UTC, shinji128 commented on app/javascript/components/LabelDelete.tsx
> +    refetchQueries: ["labels"],
ここも定例時に確認させてください！

2022-10-19 05:04 UTC, shinji128 commented on app/javascript/components/CreateLabelForm.tsx
> +      <input
[フォームタグに変更](https://github.com/mofmof/training-miura/pull/40/commits/252d959ada047fdf622493a9f9337b04efffcd07)
修正しました

2022-10-20 06:53 UTC, shwld approved these changes

2022-10-21 09:17 UTC, merged